{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ include "mecanicadm.fullname" . }}-ssm-store
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mecanicadm.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: ParameterStore
      region: {{ .Values.externalSecrets.awsRegion | quote }}
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "mecanicadm.fullname" . }}-db-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mecanicadm.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "1m" }}
  secretStoreRef:
    name: {{ include "mecanicadm.fullname" . }}-ssm-store
    kind: SecretStore
  target:
    name: {{ include "mecanicadm.fullname" . }}-db-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: {{ .Values.externalSecrets.ssmPrefix | default "/mecanicadm/prod" }}/db_host

    - secretKey: DB_PORT
      remoteRef:
        key: {{ .Values.externalSecrets.ssmPrefix | default "/mecanicadm/prod" }}/db_port

    - secretKey: DB_NAME
      remoteRef:
        key: {{ .Values.externalSecrets.ssmPrefix | default "/mecanicadm/prod" }}/db_name

    - secretKey: DB_USER
      remoteRef:
        key: {{ .Values.externalSecrets.ssmPrefix | default "/mecanicadm/prod" }}/db_user

    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecrets.ssmPrefix | default "/mecanicadm/prod" }}/db_password

    - secretKey: JWT_SECRET
      remoteRef:
        key: {{ .Values.externalSecrets.ssmPrefix | default "/mecanicadm/prod" }}/jwt_secret
{{- end }}
