{{- if .Values.kongLambda.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mecanicadm.fullname" . }}-kong-aws-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mecanicadm.labels" . | nindent 4 }}
type: Opaque
data:
  aws-access-key: {{ .Values.kongLambda.awsAccessKey | b64enc | quote }}
  aws-secret-access-key: {{ .Values.kongLambda.awsSecretAccessKey | b64enc | quote }}
{{- end }}
