{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mecanicadm.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mecanicadm.labels" . | nindent 4 }}
type: Opaque
data:
  MAIL_USERNAME: {{ .Values.secrets.data.mailUsername | default "" | b64enc | quote }}
  MAIL_PASSWORD: {{ .Values.secrets.data.mailPassword | default "" | b64enc | quote }}

  {{- if .Values.newRelic.enabled }}
  NEW_RELIC_LICENSE_KEY: {{ .Values.secrets.data.newRelicLicenseKey | default "" | b64enc | quote }}
  {{- end }}
{{- end }}
